<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>${{ values.dotnetVersion }}</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>${{ values.name }}</RootNamespace>
    <AssemblyName>${{ values.name }}</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    {%- if values.enableSwagger %}
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    {%- endif %}
    {%- if values.enableHealthChecks %}
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="8.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="8.0.1" />
    {%- endif %}
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0" />
  </ItemGroup>

</Project>
